headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
  Cookie: "" # set to your cookie

urls:
  base_filter: "https://xueqiu.com/service/screener/screen?category=CN&exchange=sh_sz&areacode=&indcode=&order_by=symbol&order=desc&page=[fill]&size=[fill]&only_count=0&current=&pct=&mc=&volume=&_=[fill]"
  base_history: "https://stock.xueqiu.com/v5/stock/chart/kline.json?symbol=[fill]&begin=[fill]&period=day&type=before&count=[fill]&indicator=kline,pe,pb,ps,pcf,market_capital,agt,ggt,balance"

settings:
  page_size: 30
  max_workers: 100
  delta_days: 500
  history_dir: "astock/history"
  log_file: "store.log"

stock_filter:
  exclude_names: ["ST"]
